functest: COS integration.
This commit  enables COS integration functional tests
for branch 24.03/stable. It includes:
  * bundles and overlays for cos-lite deployment
  * jammy-caracal test bundle updated to test integration with COS
  * Github CI actions updated to test integration with COS

func-test-pr: https://github.com/openstack-charmers/zaza-openstack-tests/pull/1324
Signed-off-by: Martin Kalcok <martin.kalcok@canonical.com>

diff --git a/ovn-dedicated-chassis/.github/workflows/tests.yml b/ovn-dedicated-chassis/.github/workflows/tests.yml
--- a/ovn-dedicated-chassis/.github/workflows/tests.yml
+++ b/ovn-dedicated-chassis/.github/workflows/tests.yml
@@ -62,6 +62,7 @@ jobs:
       - name: Install dependencies
         run: |
           sudo apt install -yqq tox python${{ matrix.python-version }}-dev
+
       - name: Run Unit tests
         run: |
           target=$(echo "${{ matrix.python-version }}" | tr -d ".")
@@ -76,6 +77,7 @@ jobs:
       - name: Install dependencies
         run: |
           sudo apt install tox
+
       - name: Run coverage
         run: |
           tox -e cover
@@ -98,6 +100,7 @@ jobs:
           sudo snap install lxd --channel 5.21/stable
           sudo snap set lxd daemon.group=adm
           sudo lxd init --auto
+
       - name: Clear FORWARD firewall rules
         run: |
           # Docker can inject rules causing firewall conflicts
@@ -105,9 +108,11 @@ jobs:
           sudo ip6tables -P FORWARD ACCEPT || true
           sudo iptables -F FORWARD  || true
           sudo ip6tables -F FORWARD || true
+
       - name: Build charm
         run: |
           tox -e build
+
       - name: Store charm as artifact
         uses: actions/upload-artifact@v4
         with:
@@ -172,6 +177,8 @@ jobs:
         run: |
           sudo apt -yqq install tox
           sudo snap install concierge --classic
+          sudo snap install juju-wait --classic
+
       - name: Prepare Environment for functional tests
         run: |
           # Use concierge to setup LXD, microk8s and bootstrap juju controller
@@ -179,12 +186,27 @@ jobs:
           juju:
             channel: 3.4/stable
           providers:
+            microk8s:
+              channel: 1.32-strict/stable
+              enable: true
+              bootstrap: false
+              addons:
+                - dns
+                - hostpath-storage
+                - metallb
             lxd:
               channel: 5.21/stable
               enable: true
               bootstrap: true
           EOF
           sudo concierge prepare -c /tmp/concierge.yaml
+          # Add microk8s as a kubernetes substrate to the Juju controller
+          sudo microk8s status --wait
+          # The kubernetes API is not always immediately available to use, even if
+          # microk8s status reports ready state. These retries ensure that we don't
+          # fail the test unnecessarily
+          (r=30;while ! juju add-k8s mk8s --controller concierge-lxd ; do ((--r))||exit;sleep 2;done)
+
       - name: Install custom functional test repository
         if: ${{ needs.parse_tags.outputs.zaza_pr != '' }}
         working-directory: ./src/
@@ -200,10 +222,20 @@ jobs:
           PR_REPO_URL=$(gh repo view --json url --jq '.url' $PR_OWNER/$PR_REPO)
           source .tox/func-target/bin/activate
           pip install --force-reinstall --no-deps git+"$PR_REPO_URL"@"$PR_BRANCH"
+
+      - name: Deploy COS lite bundle
+        working-directory: ./src/tests/bundles/
+        run: |
+          juju add-model cos-lite mk8s
+          juju deploy ./cos-lite.yaml --trust --overlay ./offers-overlay.yaml
+          juju-wait -v
+          juju status
+
       - name: Run functional tests for bundle ${{ matrix.bundle }}
         working-directory: ./src/
         run: |
           tox -e func-target -- ${{ matrix.bundle }}
+
       - name: Generate crash dumps
         if: failure()
         run: |
@@ -214,6 +246,7 @@ jobs:
           for model in $models; do
             juju-crashdump -m $model -o ./crashdumps
           done
+
       - name: Upload artifacts on failure
         if: failure()
         uses: actions/upload-artifact@v4
